# -*- coding: utf-8 -*-
# -*- mode: org -*-
#+startup: beamer
#+STARTUP: overview
#+STARTUP: indent
#+TAGS: noexport(n)

#+Title: Extensible Simulator for Replay of @@latex:\\@@ Trace Files in the Pajé Format
#+Author: Tais Loureiro Bellini
#+Date: Bachelor Dissertation Presentation  @@latex:\\@@ Porto Alegre, May 30th 2016

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [12pt,xcolor=dvipsnames,presentation]
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+STARTUP: beamer overview indent
#+LATEX_HEADER: \input{org-babel-style-preembule.tex}
#+LATEX_HEADER: \institute{
#+LATEX_HEADER:   Advised by Prof. Dr. Lucas Mello Schnorr\\
#+LATEX_HEADER:   \hfill
#+LATEX_HEADER:   \includegraphics[width=.16\textwidth]{img/inf.pdf}
#+LATEX_HEADER:   \hfill
#+LATEX_HEADER:   \includegraphics[width=.16\textwidth]{img/ufrgs.pdf}
#+LATEX_HEADER:   \hfill
#+LATEX_HEADER: }
#+LaTeX: \input{org-babel-document-preembule.tex}
#+LaTeX: \newcommand{\prettysmall}[1]{\fontsize{#1}{#1}\selectfont}

* How to export to PDF                                             :noexport:

Do: C-c C-e l P.

Note that is P instead of p.

Because you are now exporting using beamer.

* Plan                                                             :noexport:

You'll have 20 minutes if I'm right, please confirm with the secretary.

- outline                 :: 1
- motivation              :: 2-3
  - Pajé Overview - with image to illustrate entities (maybe split in
    two to have both hierarchies (types and entities))
    - the image would bethe same that is in the text but including the
      other entities so we's have all illustrated.
  - Pajé architecture - important to show later in the results that
    this may be the cause it is slower.
  - Three issues
- proposal (aiyra + plugins)  :: 4-6
  - aiyra architecture - I think the image is enough to explain
    Aiyra. Maybe some keywords. 
 - Core and plugin packages (I think it can be all in the same
   slide. They are strictly connected. The controller can be explained
   in the previous slide, it does no have many things inside it to
   highlight. The core has that part of the PajeSimulator and
   PajeContainer that is important.
- PajeNullPlugin
- PajeDumpPlugin
- PajeInserDBPlugin (I think it needs two slides)
  - The image of the dissertation, and details about the
    implementation (batches).
  - The schema
- results                 :: TBD
  - Overview (very overview about the two tests).
  * I think the methodology and results could be all together for each
    experiment. Thus we would have a full "path" for each.
  - Methodology of cpp comparison
  - Results (as many slides as results)
  - Methodology of inserdbplugin
  - Results separated by section. 
    * Figure out some type of aggrupation. Like big and medium inputs
      in the same slide.
- conclusion              :: 1
  - Positive Results (I don't think it needs an overview, just, when
    talking about the result mention the proposal. Ex: We saw that by
    deataching the core simulator and by changing the event decoding
    we got good results...).
 - Negative points: Java, JVM, memory. 
 - Things to improve: entry points
 - Future work 
- repository/marketing    :: 1
* Motivation: Pajé Context and Issues
** 
*** Context
- Trace files in the context of Performance Analysis
- Replay
- Pajé Trace File Format
- Pajé Visualization Tool and PajeNG

*** Pajé Trace File Format
- *Entities*: Container, State, Link, Variable and Event
- Types and entities hierarchy
- Header and body sections

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.75\linewidth]{./img/hierarchyex.pdf}
\end{figure}
#+END_LaTeX
 
*** PajeNG Architecture
- Core simulation in *libpaje*
- Designed to support extensions in Pajé Format 
- Simulation occurs in *PajeSimulator* and *PajeContainer* 
- *pj_dump* tool

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.75\linewidth]{./img/pajeparco.pdf}
\end{figure}
#+END_LaTeX

*** PajeNG Issues
- Extensibility 
  - little flexibility in the manipulation of data 

- Partial results
  - full set of results dumped at once

- Permanent results
 - results are discarded at the end

* Proposal: Aiyra and Plugins
** 
*** Aiyra Architecture
- Three packages: *controller*, *core simulator* and *plugin*
- Every event detected goes through all packages
- As little in memory as possible

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.65\linewidth]{./img/aiyraArchitecture.pdf}
\end{figure}
#+END_LaTeX

*** Core Simulator

- Same structure as *libpaje* 
- Generic entry points

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.6\linewidth]{./img/aiyraCorePres.pdf}
\end{figure}
#+END_LaTeX

*** Plugins

Three plugins to validate the proposal:

- *PajeNullPlugin*
  - No treatment for entities

- *PajeDumpPlugin*
  - Dump entities to standard output

- *PajeInsertDBPlugin*
  - Insert entities in a relational database

*** Paje Insert Database Plugin

- Relational Model, JDBC and MySQL
- Insertion using JDBC batches

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.6\linewidth]{./img/ermodel.pdf}
\end{figure}
#+END_LaTeX
  

* Experimental Results
** 
*** Methodology
- Full Factorial Experimental Design
- Experiments: 
  - Comparison between Aiyra and PajeNG
  - Different batch sizes in the *PajeInsertDBPlugin*


#+BEGIN_LaTeX
\begin{tabular}{l*{4}{c}r}
                 & {\bf Luiza} & {\bf Orion1} & {\bf Guarani} \\
\hline
Processor        & Intel Core i7 & Xeon E5-2630 & Intel Core i5-2400   \\
CPU(s)                   &  1                    & 2                    & 1       \\
Cores per CPU            &  4                    & 6                    & 4             \\
Max. Freq.               &  2.7 GHz              & 2.30GHz              & 3.10GHz       \\
L1d/L1i Cache            & 32/32KBytes           & 32/32KBytes          & 32/32KBytes  \\     
L2 Cache                 & 256KBytes             & 256KBytes            & 256KBytes    \\
L3 Cache                 & 6MBytes               & 15MBytes              & 6MBytes         \\
Memory                   & 16GBytes              & 32GBytes             & 20GBytes      \\\hline
OS                       & OSX 10.10.5           & Ubuntu 12.04.5       & Debian 4.3.5-1 \\\hline
\end{tabular}
#+END_LaTeX

*** Comparison Between Aiyra and PajeNG

- Evaluate the difference in the execution time
- *Factors and Levels*: 
  - Platform: luiza, orion1, guarani
  - Version: aiyra, pj, pjflex
  - Input: big, mediumm small

- *Replications*: 30


*** Results Comparison Aiyra and PajeNG

Comparison between Aiyra and PajeNG without compilation flags:

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.95\linewidth]{./img/cpp/aiyra-pj-pjflex_overview.pdf}
\end{figure}
#+END_LaTeX

*** Results Comparison Aiyra and PajeNG 

*** Different Batch Sizes in InsertDBPlugin 

*Factors and Levels:*
- Input : big, medium, small 
- Batch Size: 
       - Luiza: A, B, C, D, E, F
       - Guarani and Orion1: B, C, D, E, F
*Replications:* 
       - Luiza: 30
       - Guarani and Orion1: 10

*Java Heap Sizes:*
- Luiza: 256MBytes - 4GBytes
- Orion1: 501MBytes - 8Gbytes
- Guarani: 312Mbytes - 5Gbytes


*** Execution Time - Big and Medium Inputs

Execution time for big and medium inputs, respectively:

#+BEGIN_LaTeX
\begin{columns}
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/local_big_v2_3.pdf}
\end{figure}
\end{column}
#+END_LaTeX

#+BEGIN_LaTeX
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/local_medium_v1_3.pdf}
\end{figure}
\end{column}
\end{columns}
#+END_LaTeX

- Batch sizes without results: Java heap space exceeded
- Bigger batches increase execution time
  - Garbage Collector overhead


*** Memory Usage - Big and Medium Inputs

Memory usage for big and medium inputs, respectively:

#+BEGIN_LaTeX
\begin{columns}
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/local_mem_big_v2.pdf}
\end{figure}
\end{column}
#+END_LaTeX

#+BEGIN_LaTeX
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/local_mem_medium_v2.pdf}
\end{figure}
\end{column}
\end{columns}
#+END_LaTeX

- As expected, more memory used with bigger batches

*** Insertion Time - Big and Medium Inputs

Insertion time for big and medium inputs, respectively:

#+BEGIN_LaTeX
\begin{columns}
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/local_insert_big_v1_1.pdf}
\end{figure}
\end{column}
#+END_LaTeX

#+BEGIN_LaTeX
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/local_insert_medium_v1_1.pdf}
\end{figure}
\end{column}
\end{columns}
#+END_LaTeX

- Constant with different batch sizes

*** Execution Time - Small Input

Execution time for small input:

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.95\linewidth]{./img/batch_size/local_small_v1_3.pdf}
\end{figure}
#+END_LaTeX

*** Memory Usage - Small Input

Memory usage for small input:

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.95\linewidth]{./img/batch_size/local_mem_small_v2.pdf}
\end{figure}
#+END_LaTeX

- More susceptible to external interference changing results

*** Insertion Time - Small Input

Insertion time for small input:

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=.95\linewidth]{./img/batch_size/local_small_v1_3.pdf}
\end{figure}
#+END_LaTeX

- As expected, more insertions increase the insertion time

*** Remote Execution Time - Big and Medium Inputs

- Comparison of execution times guarani local and guarani remote

Big and medium inputs, respectively:

#+BEGIN_LaTeX
\begin{columns}
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/remote_big_v1_3.pdf}
\end{figure}
\end{column}
#+END_LaTeX

#+BEGIN_LaTeX
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/remote_medium_v1_3.pdf}
\end{figure}
\end{column}
\end{columns}
#+END_LaTeX

*** Remote Insertion Time - Big and Medium Inputs

- Comparison of insertion times guarani local and guarani remote

Big and medium inputs, respectively:

#+BEGIN_LaTeX
\begin{columns}
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/remote_insert_big_v1_3.pdf}
\end{figure}
\end{column}
#+END_LaTeX

#+BEGIN_LaTeX
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/remote_insert_medium_v1_3.pdf}
\end{figure}
\end{column}
\end{columns}
#+END_LaTeX


*** Remote - Small Input

Comparison of execution and insertion times, respectively, for small input:

#+BEGIN_LaTeX
\begin{columns}
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/remote_small_v1_3.pdf}
\end{figure}
\end{column}
#+END_LaTeX

#+BEGIN_LaTeX
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_size/remote_insert_small_v1_3.pdf}
\end{figure}
\end{column}
\end{columns}
#+END_LaTeX

*** Batch Insertion Traces - Big and Medium Inputs

Timeline of batch executions for big and medium inputs, respectively:

#+BEGIN_LaTeX
\begin{columns}
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_time/batch_time_big_v2.pdf}
\end{figure}
\end{column}
#+END_LaTeX

#+BEGIN_LaTeX
\begin{column}{.5\linewidth}
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_time/batch_time_medium_v2.pdf}
\end{figure}
\end{column}
\end{columns}
#+END_LaTeX

*** Batch Insertion Traces - Small Input

Timeline of batch executions for small input:

#+BEGIN_LaTeX
\begin{figure}[!htb]
\centering
\includegraphics[width=\linewidth]{./img/batch_time/batch_time_small_v2.pdf}
\end{figure}
#+END_LaTeX


* Conclusion and Future Work
** 
*** Conclusion and Future Work

- 


*** Thank you


